doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

## Doctrine Configuration
#doctrine:
#    dbal:
#        default_connection: application
#        connections:
#            application:
#                driver: pdo_mysql
#                host:     '%database_host%'
#                port:     '%database_port%'
#                dbname:   '%database_name%'
#                user:     '%database_user%'
#                password: '%database_password%'
#                charset:  UTF8
#                server_version: 5.6
#
#            resadec:
#                driver: pdo_pgsql
#                host:     '%resadec_db_host%'
#                port:     '%resadec_db_port%'
#                dbname:   '%resadec_db_name%'
#                user:     '%resadec_db_user%'
#                password: '%resadec_db_password%'
#                charset:  UTF8
#                server_version: 9.6.11
#    orm:
#        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#        auto_mapping: true
#        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App